import { describe, expect, it } from "vitest";
import yaml from "js-yaml";
import {
  createBlankDraft,
  createGateway,
  type EngineConfigDraft,
} from "@edumatcher/schema";
import { buildConfigDocument, generateYaml, parseYamlToDraft } from "../src/index.js";

/** Minimal two-trader exchange (design ref: config-generator §10.2). */
function twoTraderExchange(): EngineConfigDraft {
  const draft = createBlankDraft();
  draft.symbols = { AAPL: { tickDecimals: 2 } };
  draft.symbolOrder = ["AAPL"];
  draft.gateways = [
    createGateway("TRADER01", "TRADER"),
    createGateway("TRADER02", "TRADER"),
  ];
  return draft;
}

describe("buildConfigDocument", () => {
  it("emits mandatory top-level keys in builder.py order", () => {
    const doc = buildConfigDocument(twoTraderExchange());
    const keys = Object.keys(doc);
    expect(keys.slice(0, 4)).toEqual([
      "sessions_enabled",
      "enforce_collars",
      "enforce_circuit_breakers",
      "snapshot_interval_sec",
    ]);
    expect(doc.symbols).toHaveProperty("AAPL");
    expect(doc.gateways).toEqual({
      alf: [
        { id: "TRADER01", role: "TRADER", disconnect_behaviour: "CANCEL_ALL" },
        { id: "TRADER02", role: "TRADER", disconnect_behaviour: "CANCEL_ALL" },
      ],
    });
  });

  it("adds quote_refresh_policy and quote stubs for MARKET_MAKER gateways", () => {
    const draft = twoTraderExchange();
    draft.gateways.push(createGateway("MM01", "MARKET_MAKER"));
    const doc = buildConfigDocument(draft) as any;
    const mm = doc.gateways.alf.find((g: any) => g.id === "MM01");
    expect(mm.quote_refresh_policy).toBe("INACTIVATE_ON_ANY_FILL");
    expect(doc.symbols.AAPL.market_maker_quotes[0]).toMatchObject({
      gateway_id: "MM01",
      bid_price: null,
      ask_price: null,
      bid_qty: 1000,
      seed_once: true,
    });
  });

  it("seeds bid/ask around the mid-range when configured", () => {
    const draft = twoTraderExchange();
    draft.gateways.push(createGateway("MM01", "MARKET_MAKER"));
    draft.seeding.mmMidRange = { min: 100, max: 100 };
    draft.seeding.seedLastPricesFromMm = true;
    const doc = buildConfigDocument(draft) as any;
    const quote = doc.symbols.AAPL.market_maker_quotes[0];
    expect(quote.bid_price).toBeCloseTo(99.99, 5);
    expect(quote.ask_price).toBeCloseTo(100.01, 5);
    expect(doc.symbols.AAPL.last_buy_price).toBeCloseTo(100, 5);
  });

  it("converts combo leg decimal prices to ticks using tick_decimals", () => {
    const draft = twoTraderExchange();
    draft.combos = [
      {
        comboId: "C1",
        comboType: "AON",
        tif: "DAY",
        legs: [
          { symbol: "AAPL", side: "BUY", orderType: "LIMIT", quantity: 100, price: 209.5, smpAction: "NONE" },
          { symbol: "AAPL", side: "SELL", orderType: "LIMIT", quantity: 50, price: 210.5, smpAction: "NONE" },
        ],
      },
    ];
    const doc = buildConfigDocument(draft) as any;
    expect(doc.market_maker_combos[0].legs[0].price).toBe(20950);
    expect(doc.market_maker_combos[0].legs[1].price).toBe(21050);
  });
});

describe("renderYaml", () => {
  it("produces a parseable header and quoted schedule times", () => {
    const draft = twoTraderExchange();
    draft.sessionsEnabled = true;
    const text = generateYaml(draft, { generatedDate: "2026-07-09" });
    expect(text).toContain("# Generated by pm-config-gen");
    expect(text).toContain("# -- Session control --");
    // Schedule times must round-trip as strings, not sexagesimal numbers.
    const parsed = yaml.load(text, { json: true }) as any;
    expect(parsed.schedule.pre_open).toBe("09:00");
    expect(parsed.schedule.closing_auction_end).toBe("16:05");
    expect(parsed.sessions_enabled).toBe(true);
  });

  it("includes the default-field comment block when requested", () => {
    const draft = twoTraderExchange();
    draft.output.commentDefaultFields = true;
    const text = generateYaml(draft);
    expect(text).toContain("Complete Recognized Configuration Shape");
    expect(text).toContain("Field Notes and Accepted Values");
  });
});

describe("parseYamlToDraft round trip", () => {
  it("re-imports a generated config without losing modelled fields", () => {
    const draft = twoTraderExchange();
    draft.sessionsEnabled = true;
    draft.riskControls.globalStaticBandPct = 0.2;
    draft.gateways.push(createGateway("OPS01", "ADMIN"));
    const text = generateYaml(draft);
    const { draft: reparsed } = parseYamlToDraft(text);
    expect(reparsed.symbolOrder).toEqual(["AAPL"]);
    expect(reparsed.gateways.map((g) => g.id)).toEqual(["TRADER01", "TRADER02", "OPS01"]);
    expect(reparsed.gateways[2]!.role).toBe("ADMIN");
    expect(reparsed.sessionsEnabled).toBe(true);
    expect(reparsed.riskControls.globalStaticBandPct).toBeCloseTo(0.2, 5);
  });

  it("preserves unmapped top-level sections", () => {
    const text = [
      "sessions_enabled: false",
      "enforce_collars: true",
      "enforce_circuit_breakers: true",
      "snapshot_interval_sec: 0.5",
      "gateways:",
      "  alf:",
      "  - id: TRADER01",
      "    role: TRADER",
      "    disconnect_behaviour: CANCEL_ALL",
      "symbols:",
      "  AAPL:",
      "    tick_decimals: 2",
      "future_feature:",
      "  some_key: 42",
      "",
    ].join("\n");
    const { draft, unmapped } = parseYamlToDraft(text);
    expect(unmapped).toContain("future_feature");
    expect(draft.unmappedYaml.future_feature).toEqual({ some_key: 42 });
    // And it survives re-export.
    const regenerated = generateYaml(draft);
    expect(regenerated).toContain("future_feature");
  });
});
