"""The shared topic split and AuditEntry's source coordinates (task AR-1.2).

Both pm-audit-cli and pm-audit-replay have to agree on what
``order.ack.TRADER01`` means. The coverage test below is generated by walking
``spec/messages/*.yaml`` rather than listing topics by hand, so a family that
grows a new wildcard topic cannot quietly go unhandled: that is the same
discipline ``pm-msgen check`` applies to the bindings.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from edumatcher.audit.query import (
    AuditEntry,
    iter_entries,
    lookup_topic,
    split_topic,
)

SPEC_MESSAGES = Path(__file__).resolve().parents[1] / "spec" / "messages"


def _spec_topics() -> list[tuple[str, str, tuple[str, ...]]]:
    """``(family, topic_template, params)`` for every bus topic in the spec."""
    out: list[tuple[str, str, tuple[str, ...]]] = []
    for path in sorted(SPEC_MESSAGES.glob("*.yaml")):
        family = yaml.safe_load(path.read_text(encoding="utf-8"))
        for message in family["messages"]:
            topic = message.get("topic")
            if not topic:
                continue
            params = tuple(part.split("}")[0] for part in topic.split("{")[1:])
            out.append((family["family"], topic, params))
    return out


_WILDCARD_TOPICS = [t for t in _spec_topics() if t[2]]
_FIXED_TOPICS = [t for t in _spec_topics() if not t[2]]


class TestSplitTopicCoversTheSpec:
    def test_the_spec_has_wildcard_topics_to_cover(self) -> None:
        """Guards the two parametrised tests below from silently testing nothing."""
        assert len(_WILDCARD_TOPICS) > 20
        assert len(_FIXED_TOPICS) > 20

    @pytest.mark.parametrize(
        "topic,params",
        [(t, p) for _f, t, p in _WILDCARD_TOPICS],
        ids=[t for _f, t, _p in _WILDCARD_TOPICS],
    )
    def test_every_wildcard_topic_splits_into_kind_and_actor(
        self, topic: str, params: tuple[str, ...]
    ) -> None:
        actor = "ACTOR01"
        wire = topic.format(**{p: actor for p in params})
        kind, found = split_topic(wire)
        assert found == actor
        assert kind == topic[: topic.index("{")].rstrip(".")
        assert not kind.endswith(".")

    @pytest.mark.parametrize(
        "topic",
        [t for _f, t, _p in _FIXED_TOPICS],
        ids=[t for _f, t, _p in _FIXED_TOPICS],
    )
    def test_every_fixed_topic_splits_to_itself_with_no_actor(self, topic: str) -> None:
        assert split_topic(topic) == (topic, None)


class TestSplitTopicTraps:
    def test_a_fixed_topic_is_not_mistaken_for_a_wildcard(self) -> None:
        """``index.corp_action`` and ``index.corp_action_ack.{gateway_id}`` are
        different messages, and a trailing-segment split would confuse them."""
        assert split_topic("index.corp_action") == ("index.corp_action", None)
        assert split_topic("index.corp_action_ack.GW01") == (
            "index.corp_action_ack",
            "GW01",
        )

    def test_a_request_is_not_the_wildcard_it_shares_a_stem_with(self) -> None:
        """``system.symbols_request`` vs ``system.symbols.{gateway_id}``."""
        assert split_topic("system.symbols_request") == (
            "system.symbols_request",
            None,
        )
        assert split_topic("system.symbols.GW01") == ("system.symbols", "GW01")

    def test_a_one_segment_wildcard_keeps_its_family_as_the_kind(self) -> None:
        assert split_topic("book.AAPL") == ("book", "AAPL")
        assert split_topic("depth.AAPL") == ("depth", "AAPL")

    def test_an_unknown_topic_is_returned_whole(self) -> None:
        """No actor is invented; the caller raises UNKNOWN_TOPIC instead."""
        assert split_topic("wibble.frotz") == ("wibble.frotz", None)
        assert lookup_topic("wibble.frotz") is None


class TestLookupTopic:
    def test_resolves_a_wire_topic_to_its_declaring_message(self) -> None:
        entry = lookup_topic("order.ack.TRADER01")
        assert entry is not None
        assert entry["family"] == "order"
        assert entry["message"] == "order_ack"

    def test_carries_the_declared_units(self) -> None:
        """The reason the replay tool needs this at all."""
        entry = lookup_topic("order.new")
        assert entry is not None
        units = {f["name"]: f["unit"] for f in entry["fields"]}
        assert units["price_ticks"] == "ticks"


class TestAuditEntrySourceCoordinates:
    def test_absent_when_constructed_directly(self) -> None:
        entry = AuditEntry("2026-09-08T09:31:02.118+00:00", "order.new", {})
        assert entry.file is None
        assert entry.line_no == 0

    def test_to_dict_surfaces_them(self) -> None:
        entry = AuditEntry(
            "2026-09-08T09:31:02.118+00:00", "order.new", {}, file="a.log", line_no=7
        )
        assert entry.to_dict()["file"] == "a.log"
        assert entry.to_dict()["line_no"] == 7

    def test_iter_entries_numbers_raw_lines(self, tmp_path: Path) -> None:
        """The ordinal must be what ``sed -n Np`` would show, so unparseable
        lines still consume a number."""
        log = tmp_path / "audit.log"
        log.write_text(
            "\n".join(
                [
                    '[2026-09-08T09:31:02.118+00:00] [order.new] {"id": "A"}',
                    "not an audit line at all",
                    '[2026-09-08T09:31:02.121+00:00] [order.new] {"id": "B"}',
                ]
            )
            + "\n",
            encoding="utf-8",
        )
        entries = list(iter_entries([log]))
        assert [(e.payload["id"], e.line_no) for e in entries] == [("A", 1), ("B", 3)]
        assert all(e.file == str(log) for e in entries)

    def test_ordinals_restart_per_file(self, tmp_path: Path) -> None:
        first = tmp_path / "audit.log.1"
        second = tmp_path / "audit.log"
        first.write_text(
            '[2026-09-08T09:00:00.000+00:00] [order.new] {"id": "A"}\n',
            encoding="utf-8",
        )
        second.write_text(
            '[2026-09-08T09:00:01.000+00:00] [order.new] {"id": "B"}\n',
            encoding="utf-8",
        )
        entries = list(iter_entries([first, second]))
        assert [(Path(e.file or "").name, e.line_no) for e in entries] == [
            ("audit.log.1", 1),
            ("audit.log", 1),
        ]
