from __future__ import annotations

import yaml

from edumatcher.config_gen.renderer import render_yaml


def test_renderer_emits_header_and_yaml_sections() -> None:
    payload = {
        "sessions_enabled": False,
        "enforce_collars": True,
        "enforce_circuit_breakers": True,
        "snapshot_interval_sec": 0.5,
        "gateways": {
            "alf": [
                {
                    "id": "TRADER01",
                    "role": "TRADER",
                    "disconnect_behaviour": "CANCEL_ALL",
                }
            ]
        },
        "symbols": {"AAPL": {"tick_decimals": 2}},
    }

    rendered = render_yaml(
        config=payload,
        command="pm-config-gen --symbols AAPL --gateways TRADER01",
        generated_version="1.1.0",
        generated_date="2026-06-16",
    )

    assert "Generated by pm-config-gen v1.1.0" in rendered
    assert "# -- Session control --" in rendered
    assert "# -- ALF gateway allowlist --" in rendered

    # Drop comments and ensure still valid YAML mapping.
    parsed = yaml.safe_load(rendered)
    assert parsed["symbols"]["AAPL"]["tick_decimals"] == 2


def test_renderer_emits_post_trade_gateway_section() -> None:
    payload = {
        "sessions_enabled": False,
        "enforce_collars": True,
        "enforce_circuit_breakers": True,
        "snapshot_interval_sec": 0.5,
        "gateways": {
            "alf": [
                {
                    "id": "TRADER01",
                    "role": "TRADER",
                    "disconnect_behaviour": "CANCEL_ALL",
                }
            ]
        },
        "post_trade_gateway": {
            "name": "ralf-gwy01",
            "bind_address": "0.0.0.0",
            "port": 5580,
            "replay_retention_sec": 86400,
            "heartbeat_interval_sec": 1,
            "idle_timeout_sec": 5,
            "max_client_queue": 10000,
            "allowed_roles": ["CLEARING", "DROP_COPY", "AUDIT"],
        },
        "symbols": {"AAPL": {"tick_decimals": 2}},
    }

    rendered = render_yaml(
        config=payload,
        command="pm-config-gen --symbols AAPL --gateways TRADER01 --post-trade-gateway",
        generated_version="1.1.0",
        generated_date="2026-06-20",
    )

    assert "# -- RALF post-trade gateway --" in rendered
    parsed = yaml.safe_load(rendered)
    assert parsed["post_trade_gateway"]["port"] == 5580


def test_renderer_injects_stub_hint_comments() -> None:
    payload = {
        "sessions_enabled": False,
        "enforce_collars": True,
        "enforce_circuit_breakers": True,
        "snapshot_interval_sec": 0.5,
        "gateways": {
            "alf": [
                {
                    "id": "MM01",
                    "role": "MARKET_MAKER",
                    "disconnect_behaviour": "CANCEL_QUOTES_ONLY",
                }
            ]
        },
        "symbols": {
            "AAPL": {
                "tick_decimals": 2,
                "last_buy_price": None,
                "last_sell_price": None,
                "market_maker_quotes": [
                    {
                        "gateway_id": "MM01",
                        "bid_price": None,
                        "ask_price": None,
                        "bid_qty": 1000,
                        "ask_qty": 1000,
                        "tif": "DAY",
                        "seed_once": True,
                    }
                ],
            }
        },
    }

    rendered = render_yaml(
        config=payload,
        command="pm-config-gen --symbols AAPL --gateways MM01:MARKET_MAKER",
        generated_version="1.1.0",
        generated_date="2026-06-16",
    )

    assert "# WARNING: pm-config-gen cannot set prices" in rendered
    assert "bid_price: null    # REQUIRED: set display bid price" in rendered
    assert "ask_price: null    # REQUIRED: set display ask price" in rendered
    assert (
        "last_buy_price: null    # REQUIRED: set last buy reference price" in rendered
    )

    # Comments must not break YAML parsing.
    parsed = yaml.safe_load(rendered)
    assert parsed["symbols"]["AAPL"]["market_maker_quotes"][0]["bid_price"] is None
