from __future__ import annotations

import yaml

from edumatcher.config_gen.renderer import _COMMAND_WRAP_WIDTH, render_yaml


def test_renderer_emits_header_and_yaml_sections() -> None:
    payload = {
        "sessions_enabled": False,
        "enforce_collars": True,
        "enforce_circuit_breakers": True,
        "engine_tuning": {"snapshot_interval_sec": 0.5},
        "gateways": {
            "alf": [
                {
                    "id": "TRADER01",
                    "role": "TRADER",
                    "disconnect_behaviour": "CANCEL_ALL",
                }
            ]
        },
        "symbols": {"AAPL": {"tick_decimals": 2}},
    }

    rendered = render_yaml(
        config=payload,
        command="pm-config-gen --symbols AAPL --gateways TRADER01",
        generated_version="1.1.0",
        generated_date="2026-06-16",
    )

    assert "Generated by pm-config-gen v1.1.0" in rendered
    assert "# -- Session control --" in rendered
    assert "# -- Engine tuning --" in rendered
    assert "# -- ALF gateway allowlist --" in rendered

    # Drop comments and ensure still valid YAML mapping.
    parsed = yaml.safe_load(rendered)
    assert parsed["symbols"]["AAPL"]["tick_decimals"] == 2


def test_renderer_emits_post_trade_gateway_section() -> None:
    payload = {
        "sessions_enabled": False,
        "enforce_collars": True,
        "enforce_circuit_breakers": True,
        "engine_tuning": {"snapshot_interval_sec": 0.5},
        "gateways": {
            "alf": [
                {
                    "id": "TRADER01",
                    "role": "TRADER",
                    "disconnect_behaviour": "CANCEL_ALL",
                }
            ]
        },
        "post_trade_gateway": {
            "name": "ralf-gwy01",
            "bind_address": "0.0.0.0",
            "port": 5580,
            "replay_retention_sec": 86400,
            "heartbeat_interval_sec": 1,
            "idle_timeout_sec": 5,
            "max_client_queue": 10000,
            "allowed_roles": ["CLEARING", "DROP_COPY", "AUDIT"],
        },
        "symbols": {"AAPL": {"tick_decimals": 2}},
    }

    rendered = render_yaml(
        config=payload,
        command="pm-config-gen --symbols AAPL --gateways TRADER01 --post-trade-gateway",
        generated_version="1.1.0",
        generated_date="2026-06-20",
    )

    assert "# -- RALF post-trade gateway --" in rendered
    parsed = yaml.safe_load(rendered)
    assert parsed["post_trade_gateway"]["port"] == 5580


def test_renderer_injects_stub_hint_comments() -> None:
    payload = {
        "sessions_enabled": False,
        "enforce_collars": True,
        "enforce_circuit_breakers": True,
        "engine_tuning": {"snapshot_interval_sec": 0.5},
        "gateways": {
            "alf": [
                {
                    "id": "MM01",
                    "role": "MARKET_MAKER",
                    "disconnect_behaviour": "CANCEL_QUOTES_ONLY",
                }
            ]
        },
        "symbols": {
            "AAPL": {
                "tick_decimals": 2,
                "last_buy_price": None,
                "last_sell_price": None,
                "market_maker_quotes": [
                    {
                        "gateway_id": "MM01",
                        "bid_price": None,
                        "ask_price": None,
                        "bid_qty": 1000,
                        "ask_qty": 1000,
                        "tif": "DAY",
                        "seed_once": True,
                    }
                ],
            }
        },
    }

    rendered = render_yaml(
        config=payload,
        command="pm-config-gen --symbols AAPL --gateways MM01:MARKET_MAKER",
        generated_version="1.1.0",
        generated_date="2026-06-16",
    )

    assert "# WARNING: pm-config-gen cannot set prices" in rendered
    assert (
        "      # REQUIRED: set display bid price (e.g. 209.00)\n      bid_price: null"
        in rendered
    )
    assert (
        "      # REQUIRED: set display ask price (e.g. 211.00)\n      ask_price: null"
        in rendered
    )
    assert (
        "    # REQUIRED: set last buy reference price\n    last_buy_price: null"
        in rendered
    )

    # Comments must not break YAML parsing.
    parsed = yaml.safe_load(rendered)
    assert parsed["symbols"]["AAPL"]["market_maker_quotes"][0]["bid_price"] is None


def test_renderer_emits_country_section_and_hint() -> None:
    payload = {
        "sessions_enabled": False,
        "country": "Germany",
        "enforce_collars": True,
        "enforce_circuit_breakers": True,
        "engine_tuning": {"snapshot_interval_sec": 0.5},
        "gateways": {
            "alf": [
                {
                    "id": "TRADER01",
                    "role": "TRADER",
                    "disconnect_behaviour": "CANCEL_ALL",
                }
            ]
        },
        "symbols": {"AAPL": {"tick_decimals": 2}},
    }

    rendered = render_yaml(
        config=payload,
        command="pm-config-gen --symbols AAPL --gateways TRADER01 --country Germany",
        generated_version="1.1.0",
        generated_date="2026-07-26",
    )

    assert "# -- Scheduler country --" in rendered
    assert "country pm-scheduler uses for bank holidays" in rendered
    assert 'defaults to "Sweden" when omitted' in rendered

    parsed = yaml.safe_load(rendered)
    assert parsed["country"] == "Germany"


_MINIMAL_PAYLOAD = {
    "sessions_enabled": False,
    "enforce_collars": True,
    "enforce_circuit_breakers": True,
    "engine_tuning": {"snapshot_interval_sec": 0.5},
    "gateways": {
        "alf": [
            {
                "id": "TRADER01",
                "role": "TRADER",
                "disconnect_behaviour": "CANCEL_ALL",
            }
        ]
    },
    "symbols": {"AAPL": {"tick_decimals": 2}},
}


def test_short_command_is_not_wrapped() -> None:
    rendered = render_yaml(
        config=_MINIMAL_PAYLOAD,
        command="pm-config-gen --symbols AAPL --gateways TRADER01",
        generated_version="1.1.0",
        generated_date="2026-08-16",
    )

    assert "# Command: pm-config-gen --symbols AAPL --gateways TRADER01" in rendered


def test_long_command_wraps_between_options_near_target_width() -> None:
    long_command = (
        "pm-config-gen --symbols AAPL,MSFT,GOOG,AMZN "
        "--gateways TRADER01:TRADER,TRADER02:TRADER,MM01:MARKET_MAKER "
        "--country Germany --enforce-collars --enforce-circuit-breakers "
        "--post-trade-gateway --seed-mm-mid-range 0.5 "
        "--comment-default-config-fields"
    )

    rendered = render_yaml(
        config=_MINIMAL_PAYLOAD,
        command=long_command,
        generated_version="1.1.0",
        generated_date="2026-08-16",
    )

    command_lines = [
        line
        for line in rendered.splitlines()
        if line.startswith("# Command:") or line.startswith("#          ")
    ]
    assert (
        len(command_lines) > 1
    ), "a long command line should wrap onto more than one line"

    for line in command_lines[:-1]:
        assert line.endswith(" \\"), f"non-final line must end in ' \\': {line!r}"
    assert not command_lines[-1].endswith(
        "\\"
    ), "the last line must not carry a continuation character"

    for line in command_lines:
        assert line.startswith("#"), "every wrapped line must stay a YAML comment"
        assert (
            len(line) <= _COMMAND_WRAP_WIDTH
        ), f"line exceeds the configured wrap width ({_COMMAND_WRAP_WIDTH}): {line!r}"
        content = line.removesuffix("\\").rstrip()
        # Never break an option across lines -- each line ends at a space
        # boundary that was already in the source command.
        assert not content.endswith("--") or content == "#"

    # Rejoining the wrapped comment lines must reproduce the original
    # command with the same tokens, in the same order.
    rejoined = " ".join(
        line.removeprefix("# Command:").removeprefix("#").removesuffix("\\").strip()
        for line in command_lines
    )
    assert rejoined.split() == long_command.split()

    # Wrapping must not corrupt the YAML that follows.
    parsed = yaml.safe_load(rendered)
    assert parsed["symbols"]["AAPL"]["tick_decimals"] == 2


def test_empty_command_renders_a_bare_label() -> None:
    rendered = render_yaml(
        config=_MINIMAL_PAYLOAD,
        command="",
        generated_version="1.1.0",
        generated_date="2026-08-16",
    )

    assert "# Command:" in rendered
    parsed = yaml.safe_load(rendered)
    assert parsed["symbols"]["AAPL"]["tick_decimals"] == 2
