"""Default values for pm-config-gen."""

from __future__ import annotations

DEFAULT_SNAPSHOT_INTERVAL_SEC = 0.5
DEFAULT_TICK_DECIMALS = 2

DEFAULT_STATIC_BAND_PCT = 0.20
DEFAULT_DYNAMIC_BAND_PCT = 0.02

DEFAULT_CB_WINDOW_NS = 300_000_000_000
DEFAULT_CB_LEVEL_SPECS = (
    "L1:0.07:5",
    "L2:0.13:15",
    "L3:0.20",
)

DEFAULT_MM_SPREAD_TICKS = 20
DEFAULT_MM_MIN_QTY = 100
DEFAULT_MM_STUB_QTY = 1000

DEFAULT_POST_TRADE_GATEWAY_NAME = "ralf-gwy01"
DEFAULT_POST_TRADE_GATEWAY_BIND_ADDRESS = "0.0.0.0"
DEFAULT_POST_TRADE_GATEWAY_PORT = 5580
DEFAULT_POST_TRADE_GATEWAY_REPLAY_RETENTION_SEC = 86_400
DEFAULT_POST_TRADE_GATEWAY_HEARTBEAT_INTERVAL_SEC = 1
DEFAULT_POST_TRADE_GATEWAY_IDLE_TIMEOUT_SEC = 5
DEFAULT_POST_TRADE_GATEWAY_MAX_CLIENT_QUEUE = 10_000
DEFAULT_POST_TRADE_GATEWAY_ALLOWED_ROLES = ("CLEARING", "DROP_COPY", "AUDIT")

DEFAULT_MARKET_DATA_GATEWAY_NAME = "md-gwy01"
DEFAULT_MARKET_DATA_GATEWAY_BIND_ADDRESS = "0.0.0.0"
DEFAULT_MARKET_DATA_GATEWAY_PORT = 5570
DEFAULT_MARKET_DATA_GATEWAY_HEARTBEAT_INTERVAL_SEC = 1
DEFAULT_MARKET_DATA_GATEWAY_IDLE_TIMEOUT_SEC = 5
DEFAULT_MARKET_DATA_GATEWAY_REPLAY_WINDOW_SEC = 30
DEFAULT_MARKET_DATA_GATEWAY_MAX_SYMBOLS_PER_CLIENT = 200
DEFAULT_MARKET_DATA_GATEWAY_MAX_CLIENT_QUEUE = 10_000
DEFAULT_MARKET_DATA_GATEWAY_DEPTH_LEVELS = 10

DEFAULT_BALF_GATEWAY_NAME = "balf-gwy01"
DEFAULT_BALF_GATEWAY_BIND_ADDRESS = "0.0.0.0"
DEFAULT_BALF_GATEWAY_PORT = 5560
DEFAULT_BALF_GATEWAY_HEARTBEAT_INTERVAL_SEC = 1
DEFAULT_BALF_GATEWAY_HEARTBEAT_TIMEOUT_SEC = 5
DEFAULT_BALF_GATEWAY_IDLE_TIMEOUT_SEC = 30
DEFAULT_BALF_GATEWAY_AUTH_TIMEOUT_SEC = 10
DEFAULT_BALF_GATEWAY_MAX_CONNECTIONS = 64
DEFAULT_BALF_GATEWAY_MAX_CLIENT_QUEUE = 10_000
DEFAULT_BALF_GATEWAY_MAX_MESSAGES_PER_SECOND = 100
DEFAULT_BALF_GATEWAY_MAX_ERRORS_BEFORE_DISCONNECT = 10
DEFAULT_BALF_GATEWAY_ERROR_WINDOW_SEC = 60
DEFAULT_BALF_GATEWAY_DUPLICATE_SESSION_POLICY = "REJECT_NEW"

DEFAULT_API_GATEWAY_HOST = "127.0.0.1"
DEFAULT_API_GATEWAY_PORT = 8080
DEFAULT_API_GATEWAY_STATS_DB = "data/stats.db"
DEFAULT_API_GATEWAY_LOG_LEVEL = "info"
DEFAULT_API_GATEWAY_SWAGGER_ENABLED = True
DEFAULT_API_GATEWAY_RATE_LIMIT_WRITES_PER_SECOND = 10
DEFAULT_API_GATEWAY_RATE_LIMIT_BURST = 20
DEFAULT_API_GATEWAY_ENGINE_AUTH_SEC = 3.0
DEFAULT_API_GATEWAY_ENGINE_REPLY_SEC = 3.0
DEFAULT_API_GATEWAY_WAIT_ACK_SEC = 3.0
DEFAULT_API_GATEWAY_KEY_BYTES = 16

DEFAULT_SCHEDULE = {
    "pre_open": "09:00",
    "opening_auction_start": "09:25",
    "continuous_start": "09:30",
    "closing_auction_start": "16:00",
    "closing_auction_end": "16:05",
}

DEFAULT_INDEX_BASE_VALUE = 1000.0
DEFAULT_INDEX_PUBLISH_INTERVAL_SEC = 1.0
DEFAULT_INDEX_DATA_DIR = "data/indexes"
