"""Default values for pm-config-gen."""

from __future__ import annotations

DEFAULT_SNAPSHOT_INTERVAL_SEC = 0.5
DEFAULT_QUOTE_HISTORY_MAXLEN = 30
DEFAULT_DROP_COPY_BUFFER_SIZE = 10_000
DEFAULT_RECENT_TRADES_MAXLEN = 20
DEFAULT_DEPTH_SNAPSHOT_TOLERANCE_TICKS = 100
DEFAULT_TICK_DECIMALS = 2

DEFAULT_STATIC_BAND_PCT = 0.20
DEFAULT_DYNAMIC_BAND_PCT = 0.02

DEFAULT_CB_WINDOW_NS = 300_000_000_000
DEFAULT_CB_LEVEL_SPECS = (
    "L1:0.07:5",
    "L2:0.13:15",
    "L3:0.20",
)

# Automated Corridor Expansion (ACE) — see docs/user-guide/120-risk-controls.md.
DEFAULT_ACE_ENABLED = True
DEFAULT_ACE_INITIAL_BAND_PCT = 0.10
DEFAULT_ACE_RANDOM_END_MAX_NS = 30_000_000_000
#: (widen_pct, min_duration_ns) per rung; the last rung repeats indefinitely.
#: This is Nasdaq's published ladder (Rule 4120(c)(7)): 10% then 20% every
#: period thereafter.
DEFAULT_ACE_EXPANSIONS = (
    (0.10, 120_000_000_000),
    (0.20, 300_000_000_000),
)

DEFAULT_MM_SPREAD_TICKS = 20
DEFAULT_MM_MIN_QTY = 100
DEFAULT_MM_STUB_QTY = 1000

DEFAULT_POST_TRADE_GATEWAY_NAME = "ralf-gwy01"
DEFAULT_POST_TRADE_GATEWAY_BIND_ADDRESS = "0.0.0.0"
DEFAULT_POST_TRADE_GATEWAY_PORT = 5580
DEFAULT_POST_TRADE_GATEWAY_REPLAY_RETENTION_SEC = 86_400
DEFAULT_POST_TRADE_GATEWAY_HEARTBEAT_INTERVAL_SEC = 1
DEFAULT_POST_TRADE_GATEWAY_IDLE_TIMEOUT_SEC = 5
DEFAULT_POST_TRADE_GATEWAY_MAX_CLIENT_QUEUE = 10_000
DEFAULT_POST_TRADE_GATEWAY_ALLOWED_ROLES = ("CLEARING", "DROP_COPY", "AUDIT")

DEFAULT_MARKET_DATA_GATEWAY_NAME = "md-gwy01"
DEFAULT_MARKET_DATA_GATEWAY_BIND_ADDRESS = "0.0.0.0"
DEFAULT_MARKET_DATA_GATEWAY_PORT = 5570
DEFAULT_MARKET_DATA_GATEWAY_HEARTBEAT_INTERVAL_SEC = 1
DEFAULT_MARKET_DATA_GATEWAY_IDLE_TIMEOUT_SEC = 5
DEFAULT_MARKET_DATA_GATEWAY_REPLAY_WINDOW_SEC = 30
DEFAULT_MARKET_DATA_GATEWAY_MAX_SYMBOLS_PER_CLIENT = 200
DEFAULT_MARKET_DATA_GATEWAY_MAX_CLIENT_QUEUE = 10_000
DEFAULT_MARKET_DATA_GATEWAY_DEPTH_LEVELS = 10

DEFAULT_BALF_GATEWAY_NAME = "balf-gwy01"
DEFAULT_BALF_GATEWAY_BIND_ADDRESS = "0.0.0.0"
DEFAULT_BALF_GATEWAY_PORT = 5560
DEFAULT_BALF_GATEWAY_HEARTBEAT_INTERVAL_SEC = 1
DEFAULT_BALF_GATEWAY_HEARTBEAT_TIMEOUT_SEC = 5
DEFAULT_BALF_GATEWAY_IDLE_TIMEOUT_SEC = 30
DEFAULT_BALF_GATEWAY_AUTH_TIMEOUT_SEC = 10
DEFAULT_BALF_GATEWAY_MAX_CONNECTIONS = 64
DEFAULT_BALF_GATEWAY_MAX_CLIENT_QUEUE = 10_000
DEFAULT_BALF_GATEWAY_MAX_MESSAGES_PER_SECOND = 100
DEFAULT_BALF_GATEWAY_MAX_ERRORS_BEFORE_DISCONNECT = 10
DEFAULT_BALF_GATEWAY_ERROR_WINDOW_SEC = 60
DEFAULT_BALF_GATEWAY_DUPLICATE_SESSION_POLICY = "REJECT_NEW"

DEFAULT_API_GATEWAY_HOST = "0.0.0.0"
DEFAULT_API_GATEWAY_PORT = 8080
DEFAULT_API_GATEWAY_STATS_DB = "data/stats.db"
DEFAULT_API_GATEWAY_LOG_LEVEL = "info"
DEFAULT_API_GATEWAY_SWAGGER_ENABLED = True
DEFAULT_API_GATEWAY_RATE_LIMIT_WRITES_PER_SECOND = 10
DEFAULT_API_GATEWAY_RATE_LIMIT_BURST = 20
DEFAULT_API_GATEWAY_ENGINE_AUTH_SEC = 3.0
DEFAULT_API_GATEWAY_ENGINE_REPLY_SEC = 3.0
DEFAULT_API_GATEWAY_WAIT_ACK_SEC = 3.0
#: Seconds a terminal order stays in the gateway's in-memory cache before
#: eviction. 0 disables eviction, which lets the cache grow for the
#: lifetime of the process.
DEFAULT_API_GATEWAY_ORDER_RETENTION_SEC = 3600
DEFAULT_API_GATEWAY_KEY_BYTES = 16

DEFAULT_SCHEDULE = {
    "pre_open": "09:00",
    "opening_auction_start": "09:25",
    "continuous_start": "09:30",
    "closing_auction_start": "16:00",
    "closing_auction_end": "16:05",
}

DEFAULT_INDEX_BASE_VALUE = 1000.0
DEFAULT_INDEX_PUBLISH_INTERVAL_SEC = 1.0
DEFAULT_INDEX_DATA_DIR = "data/indexes"

DEFAULT_DC_GATEWAY_NAME = "dc-gwy01"
DEFAULT_DC_GATEWAY_BIND_ADDRESS = "0.0.0.0"
DEFAULT_DC_GATEWAY_PORT = 5590
DEFAULT_DC_GATEWAY_HEARTBEAT_INTERVAL_SEC = 5
DEFAULT_DC_GATEWAY_IDLE_TIMEOUT_SEC = 30
DEFAULT_DC_GATEWAY_MAX_CLIENT_QUEUE = 10_000

DEFAULT_LOG_SERVER_NAME = "log-srv01"
DEFAULT_LOG_SERVER_BIND_ADDRESS = "0.0.0.0"
DEFAULT_LOG_SERVER_PORT = 5600
DEFAULT_LOG_SERVER_DB_PATH = "data/log.db"
DEFAULT_LOG_SERVER_RETENTION_DAYS = 30
DEFAULT_LOG_SERVER_MAX_MESSAGE_BYTES = 65_536
DEFAULT_LOG_SERVER_MAX_CLIENT_QUEUE = 10_000
DEFAULT_LOG_SERVER_WRITE_BATCH_SIZE = 50
DEFAULT_LOG_SERVER_WRITE_BATCH_INTERVAL_MS = 100
DEFAULT_LOG_SERVER_HEARTBEAT_INTERVAL_SEC = 5

# LALF-PS — pm-log-srv's ZeroMQ log-distribution interface. These mirror the
# runtime defaults in edumatcher.log_srv.config; they are restated as literals
# here rather than imported for the same reason every other DEFAULT_* in this
# module is — pm-config-gen describes what a *generated file* should say, which
# is deliberately allowed to drift from what a given runtime build defaults to.
DEFAULT_LOG_SERVER_PUBSUB_ENABLED = True
DEFAULT_LOG_SERVER_PUB_PORT = 5601
DEFAULT_LOG_SERVER_PULL_PORT = 5602
DEFAULT_LOG_SERVER_LEASE_SEC = 30
DEFAULT_LOG_SERVER_MAX_LEASE_SEC = 300
DEFAULT_LOG_SERVER_MAX_SUBSCRIBERS = 32
DEFAULT_LOG_SERVER_NOTIFY_INTERVAL_MS = 250
DEFAULT_LOG_SERVER_BACKFILL_CHUNK_ROWS = 500
DEFAULT_LOG_SERVER_MAX_BACKFILL_MINUTES = 1_440
DEFAULT_LOG_SERVER_MAX_BACKFILL_ROWS = 100_000
DEFAULT_LOG_SERVER_MAX_PENDING_ROWS = 20_000
DEFAULT_LOG_SERVER_PUB_SNDHWM = 10_000
