"""YAML renderer for pm-config-gen output."""

from __future__ import annotations

from typing import Any

import yaml


def render_yaml(
    config: dict[str, Any],
    command: str,
    generated_version: str,
    generated_date: str,
    default_engine_field_comments: list[str] | None = None,
) -> str:
    lines: list[str] = [
        f"# Generated by pm-config-gen v{generated_version} on {generated_date}",
        f"# Command: {command}",
        "#",
        "# Validate with:",
        "#   poetry run python -c 'from pathlib import Path; \\",
        "#     from edumatcher.engine.config_loader import load_engine_config; \\",
        '#     print(load_engine_config(Path("engine_config.yaml")))\'',
        "",
    ]

    if default_engine_field_comments:
        lines.append("# Defaultable engine_config fields and default values:")
        for entry in default_engine_field_comments:
            if entry == "#" or entry == "":
                lines.append("#")
            else:
                lines.append(f"#   {entry}")
        lines.append("")

    section_order = [
        (
            "Session control",
            ["sessions_enabled"],
        ),
        (
            "Engine behavior",
            ["enforce_collars", "enforce_circuit_breakers", "snapshot_interval_sec"],
        ),
        ("Market-maker obligation defaults", ["mm_obligation_defaults"]),
        ("Collar profiles", ["risk_controls"]),
        ("Circuit-breaker ladder", ["circuit_breaker_defaults"]),
        ("ALF gateway allowlist", ["gateways"]),
        ("RALF post-trade gateway", ["post_trade_gateway"]),
        ("Symbol universe", ["symbols"]),
        ("Startup market-maker combo seeds", ["market_maker_combos"]),
        ("Session schedule", ["schedule"]),
    ]

    emitted_keys: set[str] = set()
    for title, keys in section_order:
        block = {k: config[k] for k in keys if k in config}
        if not block:
            continue
        lines.append(f"# -- {title} --")
        lines.append(_dump_yaml(block).rstrip())
        lines.append("")
        emitted_keys.update(block)

    remaining = {k: v for k, v in config.items() if k not in emitted_keys}
    if remaining:
        lines.append("# -- Additional fields --")
        lines.append(_dump_yaml(remaining).rstrip())
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _dump_yaml(payload: dict[str, Any]) -> str:
    dumped = yaml.safe_dump(payload, sort_keys=False)
    return "\n".join(_annotate(dumped))


def _annotate(dumped: str) -> list[str]:
    """Inject operator-facing hint comments into the serialised YAML.

    The engine rejects null bid/ask prices, so these comments turn the emitted
    stubs into an explicit fill-in checklist (design sections 6.3 and 8).
    """
    source_lines = dumped.splitlines()
    out: list[str] = []
    idx = 0
    while idx < len(source_lines):
        line = source_lines[idx]
        stripped = line.strip()
        indent = len(line) - len(line.lstrip(" "))

        if indent == 0:
            top_level_comment = _TOP_LEVEL_HINTS.get(stripped.split(":", 1)[0])
            if top_level_comment is not None:
                out.extend(_comment_lines(indent, top_level_comment))
                out.append(line)
                idx += 1
                continue

        if stripped == "market_maker_quotes:":
            out.append(line)
            block_end = idx + 1
            while block_end < len(source_lines):
                candidate = source_lines[block_end]
                candidate_indent = len(candidate) - len(candidate.lstrip(" "))
                if candidate.strip() and (
                    candidate_indent < indent
                    or (
                        candidate_indent == indent
                        and not candidate.lstrip().startswith("-")
                    )
                ):
                    break
                block_end += 1

            if any(
                source_lines[look_ahead].strip()
                in ("bid_price: null", "ask_price: null")
                for look_ahead in range(idx + 1, block_end)
            ):
                out.append(
                    " " * (indent + 2)
                    + "# WARNING: pm-config-gen cannot set prices. Fill these in before starting."
                )

            idx += 1
            continue

        suffix = _INLINE_HINTS.get(stripped)
        if suffix is not None:
            out.extend(_comment_lines(indent, suffix))
            out.append(line)
            idx += 1
            continue

        out.append(line)
        idx += 1
    return out


def _comment_lines(indent: int, hints: list[str]) -> list[str]:
    prefix = " " * indent + "# "
    return [f"{prefix}{hint}" for hint in hints]


_INLINE_HINTS: dict[str, list[str]] = {
    "bid_price: null": ["REQUIRED: set display bid price (e.g. 209.00)"],
    "ask_price: null": ["REQUIRED: set display ask price (e.g. 211.00)"],
    "last_buy_price: null": ["REQUIRED: set last buy reference price"],
    "last_sell_price: null": ["REQUIRED: set last sell reference price"],
    "halt_duration_ns: null": ["null = rest-of-day halt"],
}


_TOP_LEVEL_HINTS: dict[str, list[str]] = {
    "sessions_enabled": [
        "true lets pm-scheduler drive session transitions;",
        "false keeps the engine in continuous mode",
    ],
    "enforce_collars": ["enables per-symbol collar checks on incoming orders"],
    "enforce_circuit_breakers": ["enables per-symbol circuit-breaker enforcement"],
    "snapshot_interval_sec": [
        "seconds between book snapshot publications for dirty books"
    ],
    "mm_obligation_defaults": ["default market-maker obligation settings"],
    "risk_controls": ["collar profiles by risk level"],
    "circuit_breaker_defaults": ["circuit-breaker ladder definitions"],
    "gateways": ["ALF gateway allowlist"],
    "post_trade_gateway": ["RALF post-trade gateway settings"],
    "market_data_gateway": ["CALF market-data gateway settings"],
    "symbols": ["symbol universe"],
    "market_maker_combos": ["startup market-maker combo seeds"],
    "schedule": ["session schedule"],
}
