"""YAML renderer for pm-config-gen output."""

from __future__ import annotations

from typing import Any

import yaml


def render_yaml(
    config: dict[str, Any],
    command: str,
    generated_version: str,
    generated_date: str,
) -> str:
    lines: list[str] = [
        f"# Generated by pm-config-gen v{generated_version} on {generated_date}",
        f"# Command: {command}",
        "#",
        "# Validate with:",
        "#   poetry run python -c 'from pathlib import Path; \\",
        "#     from edumatcher.engine.config_loader import load_engine_config; \\",
        '#     print(load_engine_config(Path("engine_config.yaml")))\'',
        "",
    ]

    section_order = [
        (
            "Session control",
            ["sessions_enabled"],
        ),
        (
            "Engine behavior",
            ["enforce_collars", "enforce_circuit_breakers", "snapshot_interval_sec"],
        ),
        ("Market-maker obligation defaults", ["mm_obligation_defaults"]),
        ("Collar profiles", ["risk_controls"]),
        ("Circuit-breaker ladder", ["circuit_breaker_defaults"]),
        ("ALF gateway allowlist", ["gateways"]),
        ("RALF post-trade gateway", ["post_trade_gateway"]),
        ("Symbol universe", ["symbols"]),
        ("Startup market-maker combo seeds", ["market_maker_combos"]),
        ("Session schedule", ["schedule"]),
    ]

    emitted_keys: set[str] = set()
    for title, keys in section_order:
        block = {k: config[k] for k in keys if k in config}
        if not block:
            continue
        lines.append(f"# -- {title} --")
        lines.append(_dump_yaml(block).rstrip())
        lines.append("")
        emitted_keys.update(block)

    remaining = {k: v for k, v in config.items() if k not in emitted_keys}
    if remaining:
        lines.append("# -- Additional fields --")
        lines.append(_dump_yaml(remaining).rstrip())
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _dump_yaml(payload: dict[str, Any]) -> str:
    dumped = yaml.safe_dump(payload, sort_keys=False)
    return "\n".join(_annotate(dumped))


def _annotate(dumped: str) -> list[str]:
    """Inject operator-facing hint comments into the serialised YAML.

    The engine rejects null bid/ask prices, so these comments turn the emitted
    stubs into an explicit fill-in checklist (design sections 6.3 and 8).
    """
    out: list[str] = []
    for line in dumped.splitlines():
        stripped = line.strip()
        indent = len(line) - len(line.lstrip(" "))

        if stripped == "market_maker_quotes:":
            out.append(line)
            out.append(
                " " * (indent + 2) + "# WARNING: pm-config-gen cannot set prices. "
                "Fill these in before starting."
            )
            continue

        suffix = _INLINE_HINTS.get(stripped)
        if suffix is not None:
            out.append(f"{line}    {suffix}")
            continue

        out.append(line)
    return out


_INLINE_HINTS: dict[str, str] = {
    "bid_price: null": "# REQUIRED: set display bid price (e.g. 209.00)",
    "ask_price: null": "# REQUIRED: set display ask price (e.g. 211.00)",
    "last_buy_price: null": "# REQUIRED: set last buy reference price",
    "last_sell_price: null": "# REQUIRED: set last sell reference price",
    "halt_duration_ns: null": "# null = rest-of-day halt",
}
