"""YAML renderer for pm-config-gen output."""

from __future__ import annotations

import textwrap
from typing import Any

import yaml

# Wrap the recorded command line between options rather than leaving it as
# one very long line -- pm-config-gen invocations routinely carry a dozen+
# flags.
_COMMAND_WRAP_WIDTH = 100


def _render_command_comment(command: str) -> list[str]:
    """Render "# Command: ..." wrapped at a space between options.

    Every physical line is its own YAML comment (starts with "#"), so the
    block stays valid to parse. Continuation lines line up under the first
    word after "Command: ", so it still reads as one flowing command. All
    but the last line end in a shell continuation "\\", matching the
    "Validate with" block below, so the whole thing can be copy-pasted and
    run as-is.
    """
    label = "Command: "
    indent = " " * len(label)
    wrapped = textwrap.wrap(
        command,
        # Leave room for the "# " comment marker and the trailing " \".
        width=_COMMAND_WRAP_WIDTH - 4,
        initial_indent=label,
        subsequent_indent=indent,
        break_long_words=False,
        break_on_hyphens=False,
    )
    if not wrapped:
        return [f"# {label.rstrip()}"]
    return [
        f"# {line} \\" if i < len(wrapped) - 1 else f"# {line}"
        for i, line in enumerate(wrapped)
    ]


def render_yaml(
    config: dict[str, Any],
    command: str,
    generated_version: str,
    generated_date: str,
    default_engine_field_comments: list[str] | None = None,
) -> str:
    lines: list[str] = [
        f"# Generated by pm-config-gen v{generated_version} on {generated_date}",
        *_render_command_comment(command),
        "#",
        "# Validate with:",
        "#   poetry run python -c 'from pathlib import Path; \\",
        "#     from edumatcher.engine.config_loader import load_engine_config; \\",
        '#     print(load_engine_config(Path("engine_config.yaml")))\'',
        "",
    ]

    if default_engine_field_comments:
        lines.append("# Defaultable engine_config fields and default values:")
        for entry in default_engine_field_comments:
            if entry == "#" or entry == "":
                lines.append("#")
            else:
                lines.append(f"#   {entry}")
        lines.append("")

    section_order = [
        (
            "Session control",
            ["sessions_enabled"],
        ),
        (
            "Scheduler country",
            ["country"],
        ),
        (
            "Engine behavior",
            ["enforce_collars", "enforce_circuit_breakers"],
        ),
        (
            "Engine tuning",
            ["engine_tuning"],
        ),
        ("Market-maker obligation defaults", ["mm_obligation_defaults"]),
        ("Collar profiles", ["risk_controls"]),
        ("Circuit-breaker ladder", ["circuit_breaker_defaults"]),
        ("ALF gateway allowlist", ["gateways"]),
        ("RALF post-trade gateway", ["post_trade_gateway"]),
        ("CALF market-data gateway", ["market_data_gateway"]),
        ("Drop-copy gateway", ["dc_gateway"]),
        ("REST API gateways", ["api_gateways"]),
        ("Symbol universe", ["symbols"]),
        ("Startup market-maker combo seeds", ["market_maker_combos"]),
        ("Session schedule", ["schedule"]),
    ]

    emitted_keys: set[str] = set()
    for title, keys in section_order:
        block = {k: config[k] for k in keys if k in config}
        if not block:
            continue
        lines.append(f"# -- {title} --")
        lines.append(_dump_yaml(block).rstrip())
        lines.append("")
        emitted_keys.update(block)

    remaining = {k: v for k, v in config.items() if k not in emitted_keys}
    if remaining:
        lines.append("# -- Additional fields --")
        lines.append(_dump_yaml(remaining).rstrip())
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _dump_yaml(payload: dict[str, Any]) -> str:
    dumped = yaml.safe_dump(payload, sort_keys=False)
    return "\n".join(_annotate(dumped))


def _annotate(dumped: str) -> list[str]:
    """Inject operator-facing hint comments into the serialised YAML.

    The engine rejects null bid/ask prices, so these comments turn the emitted
    stubs into an explicit fill-in checklist (design sections 6.3 and 8).
    """
    source_lines = dumped.splitlines()
    out: list[str] = []
    idx = 0
    in_engine_tuning = False
    while idx < len(source_lines):
        line = source_lines[idx]
        stripped = line.strip()
        indent = len(line) - len(line.lstrip(" "))

        if indent == 0 and stripped:
            in_engine_tuning = stripped == "engine_tuning:"

        if indent == 0:
            top_level_comment = _TOP_LEVEL_HINTS.get(stripped.split(":", 1)[0])
            if top_level_comment is not None:
                out.extend(_comment_lines(indent, top_level_comment))
                out.append(line)
                idx += 1
                continue

        if in_engine_tuning and indent == 2 and ":" in stripped:
            tuning_comment = _ENGINE_TUNING_HINTS.get(stripped.split(":", 1)[0])
            if tuning_comment is not None:
                out.extend(_comment_lines(indent, tuning_comment))
                out.append(line)
                idx += 1
                continue

        if stripped == "market_maker_quotes:":
            out.append(line)
            block_end = idx + 1
            while block_end < len(source_lines):
                candidate = source_lines[block_end]
                candidate_indent = len(candidate) - len(candidate.lstrip(" "))
                if candidate.strip() and (
                    candidate_indent < indent
                    or (
                        candidate_indent == indent
                        and not candidate.lstrip().startswith("-")
                    )
                ):
                    break
                block_end += 1

            if any(
                source_lines[look_ahead].strip()
                in ("bid_price: null", "ask_price: null")
                for look_ahead in range(idx + 1, block_end)
            ):
                out.append(
                    " " * (indent + 2)
                    + "# WARNING: pm-config-gen cannot set prices. Fill these in before starting."
                )

            idx += 1
            continue

        suffix = _INLINE_HINTS.get(stripped)
        if suffix is not None:
            out.extend(_comment_lines(indent, suffix))
            out.append(line)
            idx += 1
            continue

        out.append(line)
        idx += 1
    return out


def _comment_lines(indent: int, hints: list[str]) -> list[str]:
    prefix = " " * indent + "# "
    return [f"{prefix}{hint}" for hint in hints]


_INLINE_HINTS: dict[str, list[str]] = {
    "bid_price: null": ["REQUIRED: set display bid price (e.g. 209.00)"],
    "ask_price: null": ["REQUIRED: set display ask price (e.g. 211.00)"],
    "last_buy_price: null": ["REQUIRED: set last buy reference price"],
    "last_sell_price: null": ["REQUIRED: set last sell reference price"],
    "halt_duration_ns: null": ["null = rest-of-day halt"],
}


_TOP_LEVEL_HINTS: dict[str, list[str]] = {
    "sessions_enabled": [
        "true lets pm-scheduler drive session transitions;",
        "false keeps the engine in continuous mode",
    ],
    "country": [
        "country pm-scheduler uses for bank holidays and local wall-clock time;",
        'accepts a country name (e.g. "Sweden") or ISO 3166-1 alpha-2 code (e.g. "SE")',
        'defaults to "Sweden" when omitted',
    ],
    "enforce_collars": ["enables per-symbol collar checks on incoming orders"],
    "enforce_circuit_breakers": ["enables per-symbol circuit-breaker enforcement"],
    "engine_tuning": [
        "runtime retention and throttling knobs with memory/latency trade-offs"
    ],
    "mm_obligation_defaults": ["default market-maker obligation settings"],
    "risk_controls": ["collar profiles by risk level"],
    "circuit_breaker_defaults": ["circuit-breaker ladder definitions"],
    "gateways": ["ALF gateway allowlist"],
    "post_trade_gateway": ["RALF post-trade gateway settings"],
    "api_gateways": ["REST/WebSocket API gateway process settings"],
    "market_data_gateway": ["CALF market-data gateway settings"],
    "dc_gateway": ["drop-copy TCP gateway settings (pm-dc-gwy)"],
    "symbols": ["symbol universe"],
    "market_maker_combos": ["startup market-maker combo seeds"],
    "schedule": ["session schedule"],
}

_ENGINE_TUNING_HINTS: dict[str, list[str]] = {
    "snapshot_interval_sec": [
        "seconds between book snapshot publications for dirty books"
    ],
    "quote_history_maxlen": ["per-gateway RECENT/ALL quote history retained in memory"],
    "drop_copy_buffer_size": ["drop-copy replay messages retained in memory"],
    "recent_trades_maxlen": ["recent trades retained per symbol snapshot"],
    "depth_snapshot_tolerance_ticks": [
        "depth window around last trade in ticks; larger values publish more depth"
    ],
}
