"""Generate the bash and zsh completion scripts for every pm-* command.

The parsers are the source of truth: each entry point in
[tool.poetry.scripts] is imported and its build_parser() rendered by shtab.
Output goes to src/edumatcher/completion/. Run `make completion` after changing
any command-line option; tests/test_shell_completion.py fails until you do.
"""

from __future__ import annotations

import argparse
import importlib
import os
import sys
import tomllib
from collections.abc import Callable
from pathlib import Path

import shtab

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "src" / "edumatcher" / "completion"
SHELLS = ("bash", "zsh")

_HEADER = {
    "bash": "# Load with: source <this file>\n",
    "zsh": '# Load with: eval "$(<this file)"  -- after compinit; `source` does NOT work\n',
}


def entry_points() -> dict[str, str]:
    with open(ROOT / "pyproject.toml", "rb") as f:
        scripts: dict[str, str] = tomllib.load(f)["tool"]["poetry"]["scripts"]
    return scripts


def build_parser_for(name: str, target: str) -> argparse.ArgumentParser:
    module = importlib.import_module(target.split(":")[0])
    factory: Callable[[], argparse.ArgumentParser] = getattr(module, "build_parser")
    saved = sys.argv[0]
    sys.argv[0] = name  # parsers without prog= take it from argv[0]
    try:
        return factory()
    finally:
        sys.argv[0] = saved


#: A few pm-* parsers embed the resolved data directory (or a path derived
#: from it, e.g. pm-viewer's --db default) in their --help text, and
#: edumatcher.config resolves that from EDUMATCHER_DATA_DIR once, at each
#: module's first import -- with a cwd-relative fallback if the directory
#: doesn't exist. Pinning it here, before any entry-point module is
#: imported, and ensuring it exists (below) makes that resolution
#: deterministic: independent of the caller's shell environment and of the
#: directory `make completion` happens to be run from. It is still the
#: project's own "installed default" path (see edumatcher.config), so it
#: still varies by home directory between machines, same as running any
#: pm-* command with --help on a fresh install would show.
_CANONICAL_DATA_DIR = "~/.local/share/edumatcher"


def render(shell: str) -> str:
    os.environ["EDUMATCHER_DATA_DIR"] = _CANONICAL_DATA_DIR
    # edumatcher.config falls back to a cwd-relative directory when the
    # pinned one does not exist, which would reintroduce the same
    # nondeterminism this is meant to remove -- so make sure it exists.
    Path(_CANONICAL_DATA_DIR).expanduser().mkdir(parents=True, exist_ok=True)
    blocks = [
        shtab.complete(build_parser_for(name, target), shell)
        for name, target in sorted(entry_points().items())
    ]
    return (
        "# GENERATED by tools/gen_completion.py -- do not edit. "
        "Regenerate with: make completion\n" + _HEADER[shell] + "\n" + "\n".join(blocks)
    )


def main() -> None:
    for shell in SHELLS:
        (OUT_DIR / f"pm-completion.{shell}").write_text(render(shell), encoding="utf-8")


if __name__ == "__main__":
    main()
