/**
 * Canonical client/server data model for the config builder.
 *
 * `EngineConfigDraft` mirrors the structure of `engine_config.yaml` directly
 * (see design §13) rather than the CLI flag surface. The CLI mini-languages are
 * strictly an input-encoding concern that the GUI avoids by editing structured
 * fields. Enum unions below mirror the Python engine models in
 * `src/edumatcher/models/`.
 */

// ---- Enums (mirror edumatcher.models.*) --------------------------------------

export const PARTICIPANT_ROLES = ["TRADER", "MARKET_MAKER", "ADMIN"] as const;
export type ParticipantRole = (typeof PARTICIPANT_ROLES)[number];

export const DISCONNECT_BEHAVIOURS = [
  "CANCEL_ALL",
  "CANCEL_QUOTES_ONLY",
  "LEAVE_ALL",
] as const;
export type DisconnectBehaviour = (typeof DISCONNECT_BEHAVIOURS)[number];

export const RESUMPTION_MODES = ["AUCTION", "CONTINUOUS"] as const;
export type ResumptionMode = (typeof RESUMPTION_MODES)[number];

export const SIDES = ["BUY", "SELL"] as const;
export type Side = (typeof SIDES)[number];

export const ORDER_TYPES = [
  "MARKET",
  "LIMIT",
  "STOP",
  "STOP_LIMIT",
  "FOK",
  "ICEBERG",
  "IOC",
  "TRAILING_STOP",
] as const;
export type OrderType = (typeof ORDER_TYPES)[number];

export const TIF_VALUES = ["DAY", "GTC", "ATO", "ATC"] as const;
export type Tif = (typeof TIF_VALUES)[number];

export const SMP_ACTIONS = [
  "NONE",
  "CANCEL_AGGRESSOR",
  "CANCEL_RESTING",
  "CANCEL_BOTH",
] as const;
export type SmpAction = (typeof SMP_ACTIONS)[number];

export const COMBO_TYPES = ["AON"] as const;
export type ComboType = (typeof COMBO_TYPES)[number];

export const DUPLICATE_SESSION_POLICIES = ["REJECT_NEW", "EVICT_OLD"] as const;
export type DuplicateSessionPolicy = (typeof DUPLICATE_SESSION_POLICIES)[number];

export const API_LOG_LEVELS = ["debug", "info", "warning", "error"] as const;
export type ApiLogLevel = (typeof API_LOG_LEVELS)[number];

export const POST_TRADE_ROLES = ["CLEARING", "DROP_COPY", "AUDIT"] as const;
export type PostTradeRole = (typeof POST_TRADE_ROLES)[number];

// ---- Personas ----------------------------------------------------------------

export const PERSONAS = ["BEGINNER", "INTERMEDIATE", "EXPERT"] as const;
export type Persona = (typeof PERSONAS)[number];

/** Persona tier ordering: higher number reveals more fields. */
export const PERSONA_RANK: Record<Persona, number> = {
  BEGINNER: 0,
  INTERMEDIATE: 1,
  EXPERT: 2,
};

/** Minimum persona tags used across field definitions ("B" | "I" | "E"). */
export type MinPersona = "B" | "I" | "E";

export function personaMeets(current: Persona, min: MinPersona): boolean {
  const minRank = min === "B" ? 0 : min === "I" ? 1 : 2;
  return PERSONA_RANK[current] >= minRank;
}

// ---- Draft model -------------------------------------------------------------

export interface Schedule {
  preOpen: string;
  openingAuction: string;
  continuous: string;
  closingAuction: string;
  closingEnd: string;
}

export interface CbLevel {
  priceShiftPct: number;
  /** null = rest of day. */
  haltDurationNs: number | null;
  resumptionMode: ResumptionMode;
}

export interface MmQuoteStub {
  gatewayId: string;
  bidPrice: number | null;
  askPrice: number | null;
  bidQty: number;
  askQty: number;
  tif: Tif;
  seedOnce: boolean;
}

/**
 * An explicit market-maker quote seed attached to a symbol. Unlike the
 * auto-generated {@link MmQuoteStub}, these are authored per-symbol in the GUI
 * and support multiple market makers per symbol (a symbol rarely has a single
 * MM in real life). `gatewayId` must reference a configured MARKET_MAKER
 * gateway (cross-checked by diagnostics).
 */
export interface MmQuoteSeed {
  gatewayId: string;
  /** Optional explicit quote label; auto-generated by the engine when omitted. */
  quoteId?: string;
  bidPrice: number | null;
  askPrice: number | null;
  bidQty: number;
  askQty: number;
  tif: Tif;
  seedOnce: boolean;
}

export interface SymbolConfig {
  tickDecimals: number;
  level?: string;
  outstandingShares?: number;
  lastBuyPrice?: number | null;
  lastSellPrice?: number | null;
  collar?: { staticBandPct?: number; dynamicBandPct?: number };
  circuitBreaker?: { levels: Record<string, Partial<CbLevel>> };
  marketMaker?: {
    enforceMmObligation?: boolean;
    mmMaxSpreadTicks?: number;
    mmMinQty?: number;
  };
  /**
   * Explicit per-symbol market-maker quote seeds. When present (non-empty),
   * these are emitted verbatim and take precedence over auto-generated stubs.
   * Supports multiple quotes (one or more MMs) per symbol.
   */
  marketMakerQuotes?: MmQuoteSeed[];
}

export interface GatewayConfig {
  id: string;
  role: ParticipantRole;
  disconnectBehaviour: DisconnectBehaviour;
  description?: string;
}

export interface RiskLevel {
  staticBandPct: number;
  dynamicBandPct: number;
}

export interface IndexConfig {
  id: string;
  description?: string;
  constituents: string[];
  baseValue: number;
  publishIntervalSec: number;
  historyFile?: string;
  stateFile?: string;
}

export interface ComboLeg {
  symbol: string;
  side: Side;
  orderType: OrderType;
  quantity: number;
  /** Decimal display price; converted to ticks on export using the symbol's tickDecimals. */
  price?: number | null;
  stopPrice?: number | null;
  smpAction: SmpAction;
}

export interface ComboConfig {
  comboId: string;
  comboType: ComboType;
  tif: Tif;
  legs: ComboLeg[];
}

export interface NetworkGatewayBase {
  enabled: boolean;
  name: string;
  bindAddress: string;
  port: number;
  heartbeatIntervalSec: number;
  idleTimeoutSec: number;
  maxClientQueue: number;
}

export interface PostTradeGatewayConfig extends NetworkGatewayBase {
  replayRetentionSec: number;
  allowedRoles: string[];
}

export interface MarketDataGatewayConfig extends NetworkGatewayBase {
  replayWindowSec: number;
  maxSymbolsPerClient: number;
}

export interface BalfGatewayConfig extends NetworkGatewayBase {
  heartbeatTimeoutSec: number;
  authTimeoutSec: number;
  maxConnections: number;
  maxMessagesPerSecond: number;
  maxErrorsBeforeDisconnect: number;
  errorWindowSec: number;
  duplicateSessionPolicy: DuplicateSessionPolicy;
}

export interface ApiCredential {
  apiKey: string;
  /** null = read-only market-data key. */
  gatewayId: string | null;
  description?: string;
}

export interface ApiGatewayConfig {
  name: string;
  enabled: boolean;
  host: string;
  port: number;
  swaggerEnabled: boolean;
  logLevel: ApiLogLevel;
  statsDb: string;
  /** ALF gateway IDs this instance is scoped to (multi-instance mode). */
  gatewayIds: string[];
  generateKeys: boolean;
  generateReadonlyKey: boolean;
  credentials: ApiCredential[];
  rateLimitWritesPerSecond: number;
  rateLimitBurst: number;
  engineAuthSec: number;
  engineReplySec: number;
  waitAckSec: number;
}

export interface EngineConfigDraft {
  sessionsEnabled: boolean;
  emitSchedule: boolean;
  snapshotIntervalSec: number;
  enforceCollars: boolean;
  enforceCircuitBreakers: boolean;
  schedule: Schedule;

  tickDecimals: number;

  symbols: Record<string, SymbolConfig>;
  /** Preserves symbol insertion order for stable output. */
  symbolOrder: string[];
  gateways: GatewayConfig[];

  riskControls: {
    /** DEFAULT level derived from global static/dynamic band, if set. */
    globalStaticBandPct?: number;
    globalDynamicBandPct?: number;
    defaultLevel?: string;
    levels: Record<string, RiskLevel>;
  };

  circuitBreakerDefaults: {
    enabled: boolean;
    windowNs: number;
    levels: Record<string, CbLevel>;
    levelOrder: string[];
  };

  mmObligationDefaults: {
    enforceMmObligation: boolean;
    mmMaxSpreadTicks: number;
    mmMinQty: number;
  };

  /** Market-maker quote seeding controls. */
  seeding: {
    mmMidRange?: { min: number; max: number };
    seedLastPricesFromMm: boolean;
    seedLastPrices: boolean;
    randomSeed?: number;
  };

  indices: IndexConfig[];
  combos: ComboConfig[];

  postTradeGateway: PostTradeGatewayConfig;
  marketDataGateway: MarketDataGatewayConfig;
  balfGateway: BalfGatewayConfig;
  apiGateways: ApiGatewayConfig[];

  output: {
    filename: string;
    commentDefaultFields: boolean;
  };

  /** YAML this GUI version does not model; preserved on export keyed by top-level section. */
  unmappedYaml: Record<string, unknown>;
}
